### ISSUE TITLE
On screen keyboard support

### ISSUE THREAD

**Issue by raboof** [SHA2017-badge/ugfx#13]
There should be an on screen keyboard in ugfx, but I haven't seen it work yet ;)

**Comment by raboof** [comment]
The keyboard in uGFX has no support for toggle (only mouse) input yet, but it appears our friends at emfcamp have added this feature: https://github.com/emfcamp/micropython/blob/tilda-master/extmod/ugfx/src/gwin/gwin_keyboard.c

I have some WiP in `dialogs.py` `prompt_text`, but that of course depends on that patch, so I'll work on that next.

**Comment by annejan** [comment]
Seems to work nicely!
Some minor issues:
SHIFT button on the OSK causes a reboot and having to press Select and A to OK is a bit weird.

**Comment by raboof** [comment]
created https://github.com/SHA2017-badge/micropython-esp32/issues/47 for 'shift'

'select and A' appears to be standard gameboy UX, though I'd like to also support 'enter', created https://github.com/SHA2017-badge/micropython-esp32/issues/48 for that.

Closing this one, follow-up tasks can be tracked through separate issues.
